Mayhem Integration initial
mayhemheroes/conllu pull request #1
Opened 2022-06-29 18:47 UTC by code-terror

2022-07-30 05:12 UTC, xansec requested changes
Please make the requested changes.

2022-07-30 05:12 UTC, xansec commented on Mayhemfile
> +project: conllu
The command is wrong here. It should just be `- cmd: fuzz-parse.py`. Otherwise you will be fuzzing `python` itself.

2022-07-30 05:12 UTC, xansec commented on tests/test_models.py
>  import unittest
Can you explain these changes? Also, if you need to add functions, please do so in a separate python module/file rather than modifying existing upstream files.

2022-07-30 05:12 UTC, xansec commented on tests/test_parser.py
>              ("1-2", (1, "-", 2)),
Can you explain these changes? Again, it's better to added needed fuzzing functionality in a separate module rather than modifying upstream.

2022-07-30 05:12 UTC, xansec commented on tests/test_readme.py
> +import contextlib
Can you explain these changes?

2022-07-30 07:30 UTC, code-terror commented on Mayhemfile
> +project: conllu
@xansec omitting python ...the analysis fails..could you diagnose the issue??

2022-08-02 05:25 UTC, xansec commented on Mayhemfile
> +project: conllu
You seem to not be capturing parse exceptions (which seems to be the normal way the project handles errors, so should not be considered a bug).  I will update this.

2022-08-02 05:38 UTC, xansec commented
Seems to be reliably hitting a `RecursionException`. We could catch this as well, but it may actually be a bug in the library (looks like infinite loop):

```
 === Uncaught Python exception: ===
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "fuzz-parse.py", line 16, in TestOneInput
    sentences=parse_tree(fdp.ConsumeString(len(data)))
  File "/conllu/__init__.py", line 49, in parse_tree
    return list(parse_tree_incr(StringIO(data)))
  File "/conllu/__init__.py", line 53, in parse_tree_incr
    yield tokenlist.to_tree()
  File "/conllu/models.py", line 184, in to_tree
    root = _create_tree(head_indexed, 0)[0]
  File "/conllu/models.py", line 171, in _create_tree
    return [
  File "/conllu/models.py", line 172, in <listcomp>
    TokenTree(child, _create_tree(head_to_token_mapping, child["id"]))
  File "/conllu/models.py", line 171, in _create_tree
    return [
  File "/conllu/models.py", line 172, in <listcomp>
    TokenTree(child, _create_tree(head_to_token_mapping, child["id"]))
  File "/conllu/models.py", line 171, in _create_tree
    return [

```

2022-08-05 16:19 UTC, xansec commented
I don't think we should catch the recursion error, as this seems to be a real bug. I'll merge in any case.

2022-08-05 16:19 UTC, merged